### Create user
# @name create_user
POST http://localhost:3000/user
Content-type: application/json

{
  "username": "the_user_name",
  "name": "The User",
  "surname": "Name",
  "age": {{ $randomInt 9 99 }},
  "password": "the_password"
}

#### Response
@user_id = {{create_user.response.body.$.id}}
@user_passoword = {{create_user.response.body.$.password}}


### Get user
# @name get_user
GET http://localhost:3000/user/{{ user_id }}

#### Response
@user_passoword = {{get_user.response.body.$.password}}


### Get user not found
# @name get_user_not_found
GET http://localhost:3000/user/-1


### Update password
# @name update_password
PUT http://localhost:3000/user/{{user_id}}/password
Content-type: application/json

{
  "password": "{{user_passoword}}",
  "newPassword": "the_new_password"
}


### Update password wrong user id
# @name update_password_wrong_user_id
PUT http://localhost:3000/user/-1/password
Content-type: application/json

{
  "password": "{{user_passoword}}",
  "newPassword": "the_new_password"
}


### Update passowrd wrong password
# @name update_password_wrong_password
PUT http://localhost:3000/user/{{user_id}}/password
Content-type: application/json

{
  "password": "{{user_passoword}}124",
  "newPassword": "the_new_password"
}
